if(LLVM_ENABLE_PGO STREQUAL "GEN")
    set(llvm_pgo "-fprofile-generate=${LLVM_PROFILE_DATA_DIR} -fprofile-update=atomic -mllvm -vp-counters-per-site=64")
elseif(LLVM_ENABLE_PGO STREQUAL "CSGEN")
    set(llvm_pgo "-fcs-profile-generate=${LLVM_PROFILE_DATA_DIR} -fprofile-update=atomic -mllvm -vp-counters-per-site=64 -fprofile-use=${LLVM_PROFDATA_FILE}")
elseif(LLVM_ENABLE_PGO STREQUAL "USE")
    set(llvm_pgo "-fprofile-use=${LLVM_PROFDATA_FILE}")
endif()
include(CheckCCompilerFlag)
check_c_compiler_flag("-mtls-dialect=gnu2" TLSDESC_AVAILABLE)
check_c_compiler_flag("-Wa,-msse2avx" SSE2AVX_AVAILABLE)
check_c_compiler_flag("-mllvm -polly -mllvm -polly-annotate-metadata-vectorize" POLLY_AVAILABLE)
set(tc_cflags "-Wno-unused-command-line-argument -g0 -fno-ident -fno-temp-file -fPIC -fno-plt -Wa,--crel,--allow-experimental-crel -fdata-sections -ffunction-sections -fseparate-named-sections -fno-unique-section-names -fno-semantic-interposition -fvisibility=hidden -fstrict-flex-arrays=3 -march=native -O3 -fno-signed-zeros -fno-trapping-math -mrecip=all -freciprocal-math -fapprox-func -ffp-contract=fast -fno-math-errno -ftls-model=local-exec -fno-unwind-tables -fno-asynchronous-unwind-tables -fsized-deallocation -fnew-infallible -faligned-allocation -Xclang -mlong-double-64 -UHAS_80_BIT_LONG_DOUBLE -DHAS_80_BIT_LONG_DOUBLE=0 -mllvm -enable-vtable-value-profiling -mllvm -enable-vtable-profile-use")
set(tc_ldflags "-fuse-ld=lld -flto-jobs=${MAKEJOBS} -Wl,--lto-whole-program-visibility,-Bsymbolic,--build-id=none,-O3,--lto-O3,--lto-CGO3,--icf=all,--gc-sections,-znow,-zrodynamic,-zpack-relative-relocs,-zcommon-page-size=2097152,-zmax-page-size=2097152,-zseparate-loadable-segments,-zkeep-text-section-prefix,-zstart-stop-visibility=hidden,-mllvm,-enable-vtable-value-profiling,-mllvm,-enable-vtable-profile-use")
if(TLSDESC_AVAILABLE)
    set(tc_cflags "${tc_cflags} -mtls-dialect=gnu2")
endif()
if(SSE2AVX_AVAILABLE)
    set(tc_cflags "${tc_cflags} -Wa,-msse2avx -mno-vzeroupper -mllvm -x86-use-vzeroupper=false")
    set(tc_ldflags "${tc_ldflags} -Wl,-mllvm,-x86-use-vzeroupper=false")
endif()
set(polly "-mllvm -polly -mllvm -polly-vectorizer=stripmine -mllvm -polly-optimizer=isl -mllvm -polly-position=before-vectorizer -mllvm -polly-loopfusion-greedy -mllvm -polly-2nd-level-tiling -mllvm -polly-register-tiling -mllvm -polly-tc-opt -mllvm -polly-run-dce -mllvm -polly-annotate-metadata-vectorize")
set(polly_lto "-Wl,-mllvm,-polly,-mllvm,-polly-vectorizer=stripmine,-mllvm,-polly-optimizer=isl,-mllvm,-polly-position=before-vectorizer,-mllvm,-polly-loopfusion-greedy,-mllvm,-polly-2nd-level-tiling,-mllvm,-polly-register-tiling,-mllvm,-polly-tc-opt,-mllvm,-polly-run-dce,-mllvm,-polly-annotate-metadata-vectorize")
if(POLLY_AVAILABLE)
   set(tc_polly "${polly}")
   set(tc_polly_lto "${polly_lto}")
endif()
set(llvm_mllvm "-mllvm -enable-masked-interleaved-mem-accesses -mllvm -enable-interleaved-mem-accesses -mllvm -slp-vectorize-hor-store -mllvm -extra-vectorizer-passes")
set(llvm_mllvm "${llvm_mllvm} -mllvm -enable-loopinterchange -mllvm -loop-interchange-reduction-to-mem -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -allow-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -aggressive-ext-opt")
set(llvm_mllvm "${llvm_mllvm} -mllvm -adce-remove-loops -mllvm -enable-ext-tsp-block-placement -mllvm -sink-common-insts=false -mllvm -vectorizer-maximize-bandwidth -mllvm -vectorizer-consider-reg-pressure -mllvm -combiner-global-alias-analysis -mllvm -optimize-regalloc -mllvm -misched-postra -mllvm -enable-gc-empty-basic-blocks -mllvm -enable-merge-functions -mllvm -mergefunc-use-aliases -mllvm -enable-jump-table-to-switch -mllvm -enable-loop-versioning-licm -mllvm -slp-revec -mllvm -slp-vectorize-non-power-of-2 -mllvm -slp-enable-strided-stores -mllvm -enable-memcpyopt-without-libcalls -mllvm -pgso=false -mllvm -enable-dfa-jump-thread -mllvm -force-ordered-reductions -mllvm -enable-histogram-loop-vectorization -mllvm -enable-ipra -mllvm -enable-spill-copy-elim -mllvm -enable-partial-inlining -mllvm -inline-enable-cost-benefit-analysis -mllvm -inline-priority-mode=cost-benefit -mllvm -inline-threshold=360 -mllvm -inlinedefault-threshold=360 -mllvm -inlinehint-threshold=525 -mllvm -unroll-full-max-count=3")
set(llvm_mllvm_lto "-Wl,-mllvm,-disable-auto-upgrade-debug-info,-mllvm,-enable-masked-interleaved-mem-accesses,-mllvm,-enable-interleaved-mem-accesses,-mllvm,-slp-vectorize-hor-store,-mllvm,-extra-vectorizer-passes")
set(llvm_mllvm_lto "${llvm_mllvm_lto} -Wl,-mllvm,-enable-loopinterchange,-mllvm,-loop-interchange-reduction-to-mem,-mllvm,-enable-loop-distribute,-mllvm,-enable-unroll-and-jam,-mllvm,-allow-unroll-and-jam,-mllvm,-enable-loop-flatten,-mllvm,-aggressive-ext-opt")
set(llvm_mllvm_lto "${llvm_mllvm_lto} -Wl,-mllvm,-adce-remove-loops,-mllvm,-enable-ext-tsp-block-placement,-mllvm,-sink-common-insts=false,-mllvm,-vectorizer-maximize-bandwidth,-mllvm,-vectorizer-consider-reg-pressure,-mllvm,-combiner-global-alias-analysis,-mllvm,-optimize-regalloc,-mllvm,-misched-postra,-mllvm,-enable-gc-empty-basic-blocks,-mllvm,-enable-merge-functions,-mllvm,-mergefunc-use-aliases,-mllvm,-enable-jump-table-to-switch,-mllvm,-enable-loop-versioning-licm,-mllvm,-slp-revec,-mllvm,-slp-vectorize-non-power-of-2,-mllvm,-slp-enable-strided-stores,-mllvm,-enable-memcpyopt-without-libcalls,-mllvm,-pgso=false,-mllvm,-enable-dfa-jump-thread,-mllvm,-force-ordered-reductions,-mllvm,-enable-histogram-loop-vectorization,-mllvm,-enable-ipra,-mllvm,-enable-spill-copy-elim,-mllvm,-enable-partial-inlining,-mllvm,-inline-enable-cost-benefit-analysis,-mllvm,-inline-priority-mode=cost-benefit,-mllvm,-inline-threshold=360,-mllvm,-inlinedefault-threshold=360,-mllvm,-inlinehint-threshold=525,-mllvm,-unroll-full-max-count=3")
if(LLVM_ENABLE_LTO STREQUAL "Thin")
    set(tc_cflags "${tc_cflags} -flto=thin -fwhole-program-vtables -fstrict-vtable-pointers -fsplit-lto-unit")
    set(tc_ldflags "${tc_ldflags} ${llvm_mllvm_lto} ${tc_polly_lto} ${tc_loop_interchange_reduction_to_mem_ld}")
    check_c_compiler_flag("-funique-source-file-names" UNIQUE_SOURCE_FILE_NAMES_AVAILABLE)
    if(UNIQUE_SOURCE_FILE_NAMES_AVAILABLE)
        set(tc_cflags "${tc_cflags} -funique-source-file-names")
    endif()
elseif(LLVM_ENABLE_LTO STREQUAL "Full")
    set(tc_cflags "${tc_cflags} -flto=full -fwhole-program-vtables -fstrict-vtable-pointers -fsplit-lto-unit")
    set(tc_ldflags "${tc_ldflags} ${llvm_mllvm_lto} ${tc_polly_lto} ${tc_loop_interchange_reduction_to_mem_ld}")
else()
    set(tc_cflags "${tc_cflags} ${llvm_mllvm} ${tc_polly} ${loop_interchange_reduction_to_mem}")
endif()
if(TOOLCHAIN_FLAGS)
    set(tc_cflags "${tc_cflags} ${TOOLCHAIN_FLAGS}")
endif()
if(CUSTOM_LIBCXX)
    set(tc_libcxx "-cxx-isystem ${CMAKE_INSTALL_PREFIX}/include/${HOST_ARCH}/c++/v1 -stdlib++-isystem ${CMAKE_INSTALL_PREFIX}/include/c++/v1 -L ${CMAKE_INSTALL_PREFIX}/lib/${HOST_ARCH}")
    set(tc_cflags "${tc_cflags} -fexperimental-relative-c++-abi-vtables -fexperimental-library -stdlib=libc++ --unwindlib=libunwind")
endif()

if(CUSTOM_COMPILER_RT)
    set(tc_compiler_rt "-resource-dir=${CMAKE_INSTALL_PREFIX}/lib/clang/${clang_version} -rtlib=compiler-rt")
endif()

if(TARGET_CPU STREQUAL "x86_64")
    set(ld_m_flag "i386pep")
    set(crt_lib "--disable-lib32 --enable-lib64")
    set(ARCH_FLAGS "-march=${MARCH} -mtune=${MTUNE}")
    set(OPT_FLAGS "-fveclib=libmvec")
    set(MLLVM_FLAGS "${llvm_mllvm} ${polly} -mllvm -polly-ignore-func=wtf -mllvm -polly-ignore-func=encode_mb")
    set(libc_strlen_builtin "0")
    if(MARCH_HAS_AVX)
        set(OPT_FLAGS "${OPT_FLAGS} -Wa,-msse2avx -mno-vzeroupper -mno-gather")
        set(MLLVM_FLAGS "${MLLVM_FLAGS} -mllvm -x86-use-vzeroupper=false")
        if(MARCH_HAS_AVX512)
            set(MLLVM_FLAGS "${MLLVM_FLAGS} -mllvm -lv-strided-pointer-ivs")
            set(OPT_FLAGS "${OPT_FLAGS} -mprefer-vector-width=512")
            set(libc_strlen_builtin "1")
        else()
            set(LLVM_ENABLE_UNSAFE_X86_AVX512_VFABI OFF)
        endif()
    endif()
    if(MARCH_HAS_APX)
        set(OPT_FLAGS "${OPT_FLAGS} -mapx-features=push2pop2,ppx,ndd,ccmp,nf,cf,zu,jmpabs -mno-apx-features=egpr")
        set(MLLVM_FLAGS "${MLLVM_FLAGS} -mllvm -x86-enable-apx-for-relocation")
    endif()
elseif(TARGET_CPU STREQUAL "aarch64")
    set(ld_m_flag "arm64pe")
    set(crt_lib "--disable-lib32 --disable-lib64 --enable-libarm64")
    set(ARCH_FLAGS "-mcpu=${MARCH}+crypto -mtune=${MTUNE} -Xclang -target-feature -Xclang +crypto")
    set(OPT_FLAGS "-fveclib=SLEEF")
    set(MLLVM_FLAGS "${llvm_mllvm} ${polly} -mllvm -polly-ignore-func=wtf -mllvm -polly-ignore-func=encode_mb -mllvm -enable-ipra=false")
    set(libc_strlen_builtin "0")
    if(MARCH_HAS_FP16)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +fullfp16")
    endif()
    if(MARCH_HAS_BF16)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +bf16")
    endif()
    if(MARCH_HAS_DOTPROD)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +dotprod")
    endif()
    if(MARCH_HAS_I8MM)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +i8mm")
    endif()
    if(MARCH_HAS_JSVT)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +jsconv")
    endif()
    if(MARCH_HAS_FP16_FML)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +fp16fml")
    endif()
    if(MARCH_HAS_SHA3)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +sha3")
    endif()
    if(MARCH_HAS_SVE)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +sve")
        set(MLLVM_FLAGS "${MLLVM_FLAGS} -mllvm -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue -mllvm -sve-tail-folding=all -mllvm -lv-strided-pointer-ivs")
        set(OPT_FLAGS "${OPT_FLAGS} -msve-vector-bits=128")
        set(libc_strlen_builtin "1")
    endif()
    if(MARCH_HAS_SVE2)
        set(ARCH_FLAGS "${ARCH_FLAGS} -Xclang -target-feature -Xclang +sve2 -Xclang -target-feature -Xclang +sve-bitperm -Xclang -target-feature -Xclang +v9a")
    endif()
endif()

if(LLVM_ENABLE_UNSAFE_X86_AVX512_VFABI)
    set(llvm_patch "llvm-custom-VecFuncs-changes-avx512.patch")
else()
    set(llvm_patch "llvm-custom-VecFuncs-changes.patch")
endif()

set(cmake_conf_args
    -GNinja
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_INSTALL_PREFIX=${MINGW_INSTALL_PREFIX}
    -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE}
    -DBUILD_SHARED_LIBS=OFF
    -DBUILD_TESTING=OFF
    -DCMAKE_C_STANDARD=17
    -DCMAKE_CXX_STANDARD=20
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
)
