ExternalProject_Add(libjxl
    DEPENDS
        lcms2
        libpng
        zlib
        brotli
        highway
    GIT_REPOSITORY https://github.com/libjxl/libjxl.git
    SOURCE_DIR ${SOURCE_LOCATION}
    GIT_CLONE_FLAGS "--depth=1 --filter=tree:0"
    GIT_PROGRESS TRUE
    GIT_REMOTE_NAME origin
    GIT_TAG main
    GIT_SUBMODULES ""
    GIT_CONFIG "submodule.recurse=false"
    UPDATE_COMMAND ""
    CONFIGURE_ENVIRONMENT_MODIFICATION
        _IS_CONFIGURE=set:1
    CONFIGURE_COMMAND ""
    COMMAND ${EXEC} ${CMAKE_COMMAND} -H<SOURCE_DIR> -B<BINARY_DIR>
        ${cmake_conf_args}
        ${libjxl_disable_sse}
        ${libjxl_force_skip_check}
        -DJPEGXL_EMSCRIPTEN=OFF
        -DJPEGXL_BUNDLE_LIBPNG=OFF
        -DJPEGXL_ENABLE_TOOLS=OFF
        -DJPEGXL_ENABLE_VIEWERS=OFF
        -DJPEGXL_ENABLE_DOXYGEN=OFF
        -DJPEGXL_ENABLE_EXAMPLES=OFF
        -DJPEGXL_ENABLE_MANPAGES=OFF
        -DJPEGXL_ENABLE_JNI=OFF
        -DJPEGXL_ENABLE_SKCMS=OFF
        -DJPEGXL_ENABLE_PLUGINS=OFF
        -DJPEGXL_ENABLE_DEVTOOLS=OFF
        -DJPEGXL_ENABLE_BENCHMARK=OFF
        -DJPEGXL_ENABLE_SJPEG=OFF
        -DJPEGXL_ENABLE_HWY_AVX3=ON
        -DJPEGXL_ENABLE_HWY_AVX3_SPR=ON
        -DJPEGXL_ENABLE_HWY_AVX3_ZEN4=ON
        -DJPEGXL_ENABLE_HWY_NEON_WITHOUT_AES=OFF
        -DJPEGXL_ENABLE_HWY_EMU128=OFF
        -DJPEGXL_ENABLE_HWY_WASM=OFF
        -DJPEGXL_ENABLE_HWY_WASM_EMU256=OFF
        -DJPEGXL_ENABLE_HWY_SCALAR=OFF
        -DJPEGXL_FORCE_SYSTEM_LCMS2=ON
        -DJPEGXL_FORCE_SYSTEM_BROTLI=ON
        -DJPEGXL_FORCE_SYSTEM_HWY=ON
        "-DCMAKE_CXX_FLAGS='-DHWY_BROKEN_SVE=0 -DHWY_BROKEN_SVE2=0 -DHWY_HAVE_RUNTIME_DISPATCH=0 -DHWY_COMPILE_ONLY_STATIC -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES'"
    BUILD_ENVIRONMENT_MODIFICATION
        _PACKAGE_NAME=set:${package}
        _BINARY_DIR=set:<BINARY_DIR>
        _FORCE_HIDE_DLLEXPORT=set:1
    BUILD_COMMAND ${EXEC} "CCC_OVERRIDE_OPTIONS='x-fno-builtin-fwrite x-fno-builtin-fread'" ninja -C <BINARY_DIR> libjxl.a libjxl_cms.a libjxl_threads.a
    INSTALL_COMMAND ${EXEC} ${CMAKE_COMMAND} --install <BINARY_DIR>
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)

force_rebuild_git(libjxl)
cleanup(libjxl install)
